
package com.mobikwik.max.undewriting.org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UWDecisionServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UWDecisionServiceSoap {


    /**
     * 
     * @param strXML
     * @param accessKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetUWDecision", action = "http://tempuri.org/GetUWDecision")
    @WebResult(name = "GetUWDecisionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetUWDecision", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetUWDecision")
    @ResponseWrapper(localName = "GetUWDecisionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetUWDecisionResponse")
    public String getUWDecision(
        @WebParam(name = "strXML", targetNamespace = "http://tempuri.org/")
        String strXML,
        @WebParam(name = "AccessKey", targetNamespace = "http://tempuri.org/")
        String accessKey);

}
