
package com.mobikwik.max.undewriting.org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UWDecisionService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://servicesone.maxbupa.com/UWDecisionService_UAT/UWDecisionService.asmx?WSDL")
public class UWDecisionService
    extends Service
{

    private final static URL UWDECISIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException UWDECISIONSERVICE_EXCEPTION;
    private final static QName UWDECISIONSERVICE_QNAME = new QName("http://tempuri.org/", "UWDecisionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://servicesone.maxbupa.com/UWDecisionService_UAT/UWDecisionService.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UWDECISIONSERVICE_WSDL_LOCATION = url;
        UWDECISIONSERVICE_EXCEPTION = e;
    }

    public UWDecisionService() {
        super(__getWsdlLocation(), UWDECISIONSERVICE_QNAME);
    }

    public UWDecisionService(WebServiceFeature... features) {
        super(__getWsdlLocation(), UWDECISIONSERVICE_QNAME, features);
    }

    public UWDecisionService(URL wsdlLocation) {
        super(wsdlLocation, UWDECISIONSERVICE_QNAME);
    }

    public UWDecisionService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UWDECISIONSERVICE_QNAME, features);
    }

    public UWDecisionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UWDecisionService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UWDecisionServiceSoap
     */
    @WebEndpoint(name = "UWDecisionServiceSoap")
    public UWDecisionServiceSoap getUWDecisionServiceSoap() {
        return super.getPort(new QName("http://tempuri.org/", "UWDecisionServiceSoap"), UWDecisionServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UWDecisionServiceSoap
     */
    @WebEndpoint(name = "UWDecisionServiceSoap")
    public UWDecisionServiceSoap getUWDecisionServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "UWDecisionServiceSoap"), UWDecisionServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UWDECISIONSERVICE_EXCEPTION!= null) {
            throw UWDECISIONSERVICE_EXCEPTION;
        }
        return UWDECISIONSERVICE_WSDL_LOCATION;
    }

}
